# This workflow builds the docs for ESPIn2020 CoastalTeam's repository

name: docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx==2.0.1
        sudo apt update -y && sudo apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
        pip install sphinx-rtd-theme
        pip install ipython
        pip install ipykernel
        pip install numpy
        pip install matplotlib==3.3.1
    - name: Build and test documentation
      run: |
        (cd docs && make docs)
        (cd docs && make html)
    - name: Debug
      run: |
        echo $REF
        echo $EVENT_NAME
        echo ${{ github.event_name == 'push' }}
        echo ${{ github.ref == 'refs/heads/master' }}
        echo ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.5
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          REF: ${{ github.ref }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
